### PR TITLE
Setup and README update for full transform and index (RPB-18)

### PR DESCRIPTION
**Pull request by fsteeg**
See http://rpb.lobid.org/search and setup at `sol@quaoar2:~/git/rpb`.

Code review: @dr0i (to be assigned by @acka47 after functional review of RPB-18).

### CODE REVIEW

**Comment by acka47** [comment]
I gave my +1 in RPB-18. @dr0i can do the functional review now.

**Comment by dr0i** [comment]
When doing `sh validateJsonOutput.sh` I got:
>error:  /home/pc/git/rpb/conf/output/test-output-31.json: Unexpected end of JSON input

When doing `test-only tests.CITests` I got:
> [error] application - Could not get classification data, index: nwbib type: json-ld-nwbib-spatial, id: https://nwbib.de/spatial#N58 ({}: {})

**Comment by dr0i** [comment]
Sorry , pushed this accidentially to the `main` branch. Force pushed the reversion.

**Comment by dr0i** [comment]
Oh, not possible to reopen a merged PR ... gonna try  the `Revert` button in github now...

**Comment by acka47** [comment]
>When doing `sh validateJsonOutput.sh` I got:
>>error:  /home/pc/git/rpb/conf/output/test-output-31.json: Unexpected end of JSON input

This can be ignored for now. It is because the transformation generates one empty file.

**Comment by fsteeg** [comment]
> [error] application - Could not get classification data, index: nwbib type: json-ld-nwbib-spatial, id: https://nwbib.de/spatial#N58 ({}: {})

Right, but the build does not fail, and this is independent of this PR.

**Pull request merged**
