### PR TITLE
Add lookup for relatedPersons without gndId (rpb-120)

### PR DESCRIPTION
**Pull request by maipet**
Adjust lookup tabels for relatedPersons
Add new example to test records

### CODE REVIEW

**Comment by fsteeg** [comment]
Result looks good, deployed to test: http://test.rppd.lobid.org/1190213958

About the TSV files:

- How did you update `gndId-to-rppdId.tsv`? Just by runnging `gndId-to-rppdId.tsv`? We should probably add running that workflow to the scripts.
- How did you create `rppdId-with-label.tsv`? We should also automate and integrate that like for the one above.

**Comment by maipet** [comment]
I actually edited `gndId-to-rppdId.tsv` directly with a regex. I'll update the existing mapping-fix and deploy the workflow for `ppdId-with-label.tsv` and newest tsv as well in a new step (some records of the original export has changed, so that the tsv are not up-to-date at the moment)

**Comment by fsteeg** [comment]
OK, I updated the `transformRppd.sh` script for what I understand is required for the full run. I updated the input file names in `rppd-to-gnd-mapping.flux` and `rppd-rppdId-with-label-map.flux` to fit with the other workflows.

I think we should not check in manual changes like the encoding issues, since these are overwritten on the full run. (I guess they are actually errors in the incoming data and should be fixed in Allegro?).

I created the lookup tables with today's `RPBEXP.zip` data (see `transformAndIndex.sh`), transformed the test data, and checked in the result. If that looks good to you @maipet I'll do the full run on the server for a new index.

**Comment by maipet** [comment]
okay, sounds good and the test data I checked looks good. 
To the encoding-issue: should I create a Jira ticket for pk06410 and pta0927 to fix it in Allegro?

**Comment by fsteeg** [comment]
Redeployed to test, still looks good: http://test.rppd.lobid.org/1190213958

Will deploy to production and merge.

> should I create a Jira ticket for pk06410 and pta0927 to fix it in Allegro?

Yes, sounds good (though I'm not sure it's actually a data entry issue in Allegro, but that would be my suspicion since encoding is correct elsewhere).

**Pull request merged**
