### PR TITLE
Add f71, f86, update f87

### PR DESCRIPTION
**Pull request by acka47**
Resolves import fix and flux for RPB-61.

This is wip. I already did the following:

- Update enum values for resource types
- Also update test data and README accordingly.
- Update import flux to local strapi instance.

To Do:
- [x] adjust fix for `f87`
- ~~[ ] add `f71`~~
- [x] add `f86` test data

### CODE REVIEW

**Comment by fsteeg** [comment]
See test deployment information at: https://jira.hbz-nrw.de/browse/RPB-61?focusedId=306832&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-306832

**Comment by fsteeg** [comment]
As far as I see, this has not been reviewed (here or in https://jira.hbz-nrw.de/browse/RPB-61), requesting review from @acka47.

**Comment by fsteeg** [comment]
Can' formally request review since you originally opened it, just give a +1 here or in https://jira.hbz-nrw.de/browse/RPB-61, @acka47.

**Comment by acka47** [comment]
+1

**Pull request merged**
