### PR TITLE
Update metafacture dependencies (#24)

### LINKED ISSUE #24: Build fails with NoSuchFieldError: EOF_TOKEN
Since  [metafix 0.4.0-SNAPSHOT uses rc versions of metafacture-core](https://github.com/metafacture/metafacture-fix/pull/266/commits/71da106651f871ed8fea4dbfd579c94303ad04aa) the build fails with:
> org.metafacture.commons.reflection.ReflectionException: class could not be instantiated: class org.metafacture.metafix.Metafix
[...]
Caused by: java.lang.NoSuchFieldError: EOF_TOKEN

Relates to https://github.com/metafacture/metafacture-fix/pull/266.

### PR DESCRIPTION
**Pull request by dr0i**
Also pin antlr-runtime to 3.2.
This makes the build sucessful again.

Resolves #24.

### CODE REVIEW

**Comment by dr0i** [comment]
This PR is deployed on quaoar2.

**Comment by fsteeg** [comment]
Thanks, and that works. However I think we should reconsider if we actually want to depend on the Fix master here in rpb. The rpb build broke without any changes or updates to rpb, I think this shows that the current setup is not stable enough. We did not need any new features here, so it would have been better to depend on a stable version.

To also have a way to quickly make new features available in rpb in a controlled way, I think the best approach is to consume a dedicated `rpb` branch of Fix, which I've pushed with the newest state of Fix that still consumes Core via Central (not GitHub Packages), which is about a month old. No newer features are currently used in rpb, and this way no updates to the Fix master can interfere with rpb. 

What do you think @dr0i?

**Comment by dr0i** [comment]
Yes, make sense.  Until we have a regular release of metafacture-fix this should be safer.

**Comment by fsteeg** [comment]
I was going to deploy this, but while this works in a clean CI environment, it won't work for our deployment setup, as the checked out version of metafacture-fix will conflict with the usage in other projects like lobid-resources and playground. Longer-term, we will containerize, which should improve these kinds of problems.

Short term, for this PR, I reverted to the original proposal by @dr0i, plus some tweaks: checkout correct branch, remove the cache (which we don't need if we actually build the correct version), unify the dependency exlusion mechanism, and change the lookup paths to include leading `./`. (I had to delete the local gradle cache with `rm -rf  ~/.gradle/caches/` to get consistent results both locally and in the GitHub action, I could then reproduce the original `NoSuchFieldError: EOF_TOKEN` issue from #24). Will deploy and merge.

**Pull request closed without merging**
